name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Railway
      uses: railwayapp/action@v1
      with:
        railway-token: ${{ secrets.RAILWAY_TOKEN }}